# kind-cluster-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Control Plane Nodes
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80 # HTTP
        hostPort: 80
        protocol: TCP
      - containerPort: 443 # HTTPS
        hostPort: 443
        protocol: TCP
  # Worker Nodes with Port Forwarding for Ingress
  - role: worker
  - role: worker
  - role: worker
