---
apiVersion: v1
kind: Namespace
metadata:
  name: stress
---
apiVersion: v1
kind: Pod
metadata:
  name: stress-pod2
  namespace: stress
spec:
  containers:
    - name: stress
      image: docker.io/polinux/stress-ng:latest
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "50m"
          memory: "50Mi"
      command: ["stress-ng"]
      args:
        ["--cpu", "2", "--vm", "2", "--vm-bytes", "500M", "--timeout", "3600"]
